version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
          name: Build
          command: 'go build'
  test:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
          name: Tests
          command:  'go test -v -race -coverprofile cover.out'
      - run: 
          name: Generate code coverage
          command: 'sed -i "s/_$(pwd|sed 's/\//\\\//g')/./g" cover.out; go tool cover -html=cover.out -o coverage.html'
      - store_artifacts:
          path: coverage.html
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
