version: 2
jobs:
  build:
    docker:
      image: circleci/golang:1.10
    steps:
      - checkout
      - run: go build
  test:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go test -v -race -coverprofile cover.out
      - run: go tool cover -html=cover.out -o $CIRCLE_TEST_REPORTS/coverage.html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
